name: Terraform Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply or destroy)'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::877786395093:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd Infra
          terraform init

      - name: Terraform fmt
        run: |
           cd Infra
           terraform fmt

      - name: Terraform Validate
        run: |
          cd Infra
          terraform validate

      - name: Terraform plan
        run:  terraform plan -var-file=env/dev/terraform.tfvars

      - name: Terraform Apply or Destroy
        run: |
              if [ "${{ github.event.inputs.action }}" == "apply" ]; then
                terraform apply -var-file=env/dev/terraform.tfvars -auto-approve
              elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
                terraform destroy -var-file=env/dev/terraform.tfvars -auto-approve
              fi
